name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver string'
        required: true
        type: string
jobs:
  assets:
    name: 'Create Release Assets'
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Tools'
        run: |
          sudo apt update
          sudo apt install coreutils xxd grep sed zip jq
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Create index.html'
        run: |
          SCRIPTJS=`echo -n "sha256-" && sha256sum -b script.js | grep -o '^[0-9a-f]\+' | xxd -r -p | base64`
          LANGJS=`echo -n "sha256-" && sha256sum -b language.js | grep -o '^[0-9a-f]\+' | xxd -r -p | base64`
          STYLECSS=`echo -n "sha256-" && sha256sum -b style.css | grep -o '^[0-9a-f]\+' | xxd -r -p | base64`
          cat dev.html | sed "s|src=\"script.js\"|src=\"script.js\" integrity=\"$SCRIPTJS\"| ; s|src=\"language.js\"|src=\"language.js\" integrity=\"$LANGJS\"| ; s|href=\"style.css\"|href=\"style.css\" integrity=\"$STYLECSS\"|" - > index.html
      - id: create-tarxz
        name: 'Create TAR.XZ'
        run: tar -cJvf mahjongg-${{ inputs.version }}.tar.xz background.webp index.html language.js LICENSE script.js style.css
      - id: create-zip
        name: 'Create ZIP'
        run: zip -j mahjongg-${{ inputs.version }}.zip background.webp index.html language.js LICENSE script.js style.css
      - name: 'Upload artifact TAR.XZ'
        uses: actions/upload-artifact@v4
        with:
          name: artifact-tarxz
          path: mahjongg-${{ inputs.version }}.tar.xz
      - name: 'Upload artifact ZIP'
        uses: actions/upload-artifact@v4
        with:
          name: artifact-zip
          path: mahjongg-${{ inputs.version }}.zip
        
  create-release:
    name: 'Create Release'
    needs: assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:       
      - name: 'Create release'
        run: |
          rlsupurl=$(gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$OWNER/$REPO/releases -f "tag_name=$RELVER" -f "target_commitish=master" -f "name=$RELVER" -f "body=Automatic release $RELVER" -F "draft=false" -F "prerelease=false" -F "generate_release_notes=true" | jq .upload_url | sed 's/{?name,label}//' -)
          echo 'RLS_UPLOAD_URL_TARXZ='$rlsupurl'?name=mahjongg-'$RELVER'.tar.xz' >> $GITHUB_ENV
          echo 'RLS_UPLOAD_URL_ZIP='$rlsupurl'?name=mahjongg-'$RELVER'.zip' >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          RELVER: ${{ inputs.version }}
      - name: 'Download artifact TAR.XZ'
        uses: actions/download-artifact@v4
        with:
          name: artifact-tarxz
      - name: 'Download artifact ZIP'
        uses: actions/download-artifact@v4
        with:
          name: artifact-zip
      - name: 'Show me what you got'
        run: ls -l
#      - name: 'Upload release asset TAR.XZ'
#        run: |
#          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" $RLS_UPLOAD_URL_TARXZ -f "@mahjongg-$RELVER.tar.xz"
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          OWNER: ${{ github.repository_owner }}
#          REPO: ${{ github.event.repository.name }}
#          RELVER: ${{ inputs.version }}
