name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver string'
        required: true
        type: string
jobs:
  sri:
    name: 'Subresource Integrity'
    runs-on: ubuntu-latest
    steps:
      - id: sri1
        name: 'Install utils'
        run: |
          sudo apt update
          sudo apt install coreutils grep xxd sed
      - id: sri2
        name: 'Checkout'
        uses: actions/checkout@master
      - id: sri3
        name: 'Create index.html'
        run: |
          SCRIPTJS=`echo -n "sha256-" && sha256sum -b script.js | grep -o '^[0-9a-f]\+' | xxd -r -p | base64`
          LANGJS=`echo -n "sha256-" && sha256sum -b language.js | grep -o '^[0-9a-f]\+' | xxd -r -p | base64`
          STYLECSS=`echo -n "sha256-" && sha256sum -b style.css | grep -o '^[0-9a-f]\+' | xxd -r -p | base64`
          cat dev.html | sed "s|src=\"script.js\"|src=\"script.js\" integrity=\"$SCRIPTJS\"| ; s|src=\"language.js\"|src=\"language.js\" integrity=\"$LANGJS\"| ; s|href=\"style.css\"|href=\"style.css\" integrity=\"$STYLECSS\"|" - > index.html
      - id: sri4
        name: 'Store artifact'
        uses: actions/upload-artifact@v4
        with:
          name: index-html
          path: index.html
